sudo: false
language: c
env:
  global:
  - SHADOWSOCKS_LIBEV_VERSION=3.0.8
  matrix:
  - TOOLCHAIN=arm
cache:
  directories:
  - "$HOME/CACHE"
script: make package TOOLCHAIN=${TOOLCHAIN} SHADOWSOCKS_LIBEV_VERSION=${SHADOWSOCKS_LIBEV_VERSION} SHADOWSOCKS_LIBEV_RELEASE_VERSION=${TRAVIS_TAG:-"${SHADOWSOCKS_LIBEV_VERSION}-${TRAVIS_COMMIT:0:8}"}
deploy:
  provider: releases
  api_key: 
  - "${GitHub_TOKEN}"
  file:
  - "${HOME}/shadowsocks-libev-${TRAVIS_TAG}-${TOOLCHAIN}.tar.gz"
  skip_cleanup: true
  on:
    tags: true

addons:
  apt:
    packages:
    - autoconf
    - automake
    - bison
    - bzip2
    - diffutils
    - flex
    - m4
    - build-essential
    - gawk
    - groff-base
    - libtool
    - libslang2
    - make
    - patch
    - perl
    - pkg-config
    - shtool
    - texinfo
    - zlib1g-dev
    - gettext
    - libexpat1-dev
    - libssl-dev
    - gperf
    - python
    - libxml-parser-perl
    - gcc-multilib
    - libxml2-dev
    - g++-4.4
    - g++-multilib
    - libncurses5-dev
    - libstdc++6-4.4-dev
    - libvorbis-dev
    - g++-4.4-multilib
    - autopoint
    - autogen
    - sed
    - intltool
    - libelf1:i386
    - libglib2.0-dev
    - lib32z1-dev
    - lib32stdc++6
    - wget
